"""Add Bingo tables

Revision ID: 06c12b1dbd7c
Revises: 3cd504dbda82
Create Date: 2026-04-29 15:30:54.415248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c12b1dbd7c'
down_revision: Union[str, Sequence[str], None] = '3cd504dbda82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bingo_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'active', 'finished', name='bingosessionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('drawn_numbers', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bingo_sessions_id'), 'bingo_sessions', ['id'], unique=False)
    op.create_table('bingo_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('grid', sa.JSON(), nullable=False),
    sa.Column('marked_numbers', sa.JSON(), nullable=True),
    sa.Column('is_winner', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['bingo_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bingo_cards_id'), 'bingo_cards', ['id'], unique=False)
    op.create_index(op.f('ix_bingo_cards_session_id'), 'bingo_cards', ['session_id'], unique=False)
    op.create_index(op.f('ix_bingo_cards_user_id'), 'bingo_cards', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bingo_cards_user_id'), table_name='bingo_cards')
    op.drop_index(op.f('ix_bingo_cards_session_id'), table_name='bingo_cards')
    op.drop_index(op.f('ix_bingo_cards_id'), table_name='bingo_cards')
    op.drop_table('bingo_cards')
    op.drop_index(op.f('ix_bingo_sessions_id'), table_name='bingo_sessions')
    op.drop_table('bingo_sessions')
    # ### end Alembic commands ###
